//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transporterQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int ContainerID { get; set; }
        public int ShipmentID { get; set; }
        public Nullable<System.DateTime> ScheduleFromDT { get; set; }
        public Nullable<System.TimeSpan> ScheduleTime { get; set; }
        public int SlotID { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public int UpdatedByUserID { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<System.DateTime> VehicleArrivalDT { get; set; }
        public int VehicleArrivalByUserID { get; set; }
        public Nullable<System.DateTime> LoadingDT { get; set; }
        public int LoadingByUserID { get; set; }
        public Nullable<System.DateTime> DispatchedDT { get; set; }
        public int DispatchedByUserID { get; set; }
        public Nullable<System.DateTime> DeliveryDT { get; set; }
        public int DeliveryByUserID { get; set; }
        public string CtrName { get; set; }
    }
}
