//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transporterQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Executive
    {
        public int ExecutiveID { get; set; }
        public string ExecutiveName { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public bool CanCreateRFQ { get; set; }
        public bool CanSelectTransporter { get; set; }
        public bool CanCloseRFQ { get; set; }
        public bool CanSelectForCustomer { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public System.DateTime UpdatedDT { get; set; }
        public bool IsDeleted { get; set; }
        public string ZoneIDs { get; set; }
        public string Rights { get; set; }
        public string ServiceRights { get; set; }
    }
}
