//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transporterQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotations
    {
        public int QuoteID { get; set; }
        public int RequestForQuoteID { get; set; }
        public int TransporterID { get; set; }
        public int AcceptID { get; set; }
        public bool IsAcceptedByExeOrCust { get; set; }
        public decimal Charges { get; set; }
        public string PaymentTerms { get; set; }
        public string Status { get; set; }
        public System.DateTime AcceptanceStatusOn { get; set; }
        public Nullable<System.DateTime> ExtendDeliveryDT { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public System.DateTime UpdatedDT { get; set; }
        public bool IsDeleted { get; set; }
        public string Components { get; set; }
        public decimal ExchangeRate { get; set; }
        public string AcceptNote { get; set; }
        public int RoundNumber { get; set; }
        public string NegotiationComments { get; set; }
        public bool IsNegotiated { get; set; }
    }
}
