//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transporterQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteType
    {
        public int QuoteTypeID { get; set; }
        public string QuoteTypeName { get; set; }
        public string PaidBy { get; set; }
        public string Type { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDT { get; set; }
        public Nullable<int> LastUpdatedByUserID { get; set; }
        public bool IsAllowNegotiation { get; set; }
        public int ServiceTypeID { get; set; }
        public string CoreField { get; set; }
    }
}
