//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transporterQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQFieldValue
    {
        public int RFQFieldID { get; set; }
        public int RFQID { get; set; }
        public int FieldID { get; set; }
        public string FieldValue { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public int CreatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
