//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transporterQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public int ServiceTypeID { get; set; }
        public string ServiceName { get; set; }
        public bool IsDeleted { get; set; }
        public string CompletionDateText { get; set; }
        public string PickupDateText { get; set; }
    }
}
