//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transporterQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipField
    {
        public int ShipFieldID { get; set; }
        public int QuoteTypeID { get; set; }
        public string PickupDTName { get; set; }
        public string ProductName { get; set; }
        public string SourceLocationName { get; set; }
        public string SourceAddressName { get; set; }
        public string DestinationName { get; set; }
        public string ContainerName { get; set; }
        public string PortofLoadingName { get; set; }
        public string PortofDischargeName { get; set; }
        public string EmtcontainPickupName { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public bool IsDeleted { get; set; }
    }
}
