//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transporterQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public int SourceID { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public System.DateTime UpdatedDT { get; set; }
        public bool IsDeleted { get; set; }
    }
}
