//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Config
{
    public int ConfigID { get; set; }
    public string Field { get; set; }
    public string Value { get; set; }
    public System.DateTime CreatedDT { get; set; }
}

public partial class Container
{
    public int ContainerID { get; set; }
    public int ShipmentID { get; set; }
    public Nullable<System.DateTime> ScheduleFromDT { get; set; }
    public Nullable<System.TimeSpan> ScheduleTime { get; set; }
    public int SlotID { get; set; }
    public string Notes { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public int CreatedByUserID { get; set; }
    public Nullable<System.DateTime> UpdatedDT { get; set; }
    public int UpdatedByUserID { get; set; }
    public bool IsDeleted { get; set; }
    public string Status { get; set; }
    public string VehicleNumber { get; set; }
    public Nullable<System.DateTime> VehicleArrivalDT { get; set; }
    public int VehicleArrivalByUserID { get; set; }
    public Nullable<System.DateTime> LoadingDT { get; set; }
    public int LoadingByUserID { get; set; }
    public Nullable<System.DateTime> DispatchedDT { get; set; }
    public int DispatchedByUserID { get; set; }
    public Nullable<System.DateTime> DeliveryDT { get; set; }
    public int DeliveryByUserID { get; set; }
    public string CtrName { get; set; }
}

public partial class Customer
{
    public int CustomerID { get; set; }
    public string CompanyName { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Mobile { get; set; }
    public string AlternateMobile { get; set; }
    public string Password { get; set; }
    public string Notes { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public System.DateTime UpdatedDT { get; set; }
    public bool IsDeleted { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string Country { get; set; }
}

public partial class Executive
{
    public int ExecutiveID { get; set; }
    public string ExecutiveName { get; set; }
    public string Designation { get; set; }
    public string Email { get; set; }
    public string Mobile { get; set; }
    public string Password { get; set; }
    public bool CanCreateRFQ { get; set; }
    public bool CanSelectTransporter { get; set; }
    public bool CanCloseRFQ { get; set; }
    public bool CanSelectForCustomer { get; set; }
    public string Notes { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public System.DateTime UpdatedDT { get; set; }
    public bool IsDeleted { get; set; }
    public string ZoneIDs { get; set; }
    public string Rights { get; set; }
    public string ServiceRights { get; set; }
}

public partial class Field
{
    public int FieldID { get; set; }
    public string FieldName { get; set; }
    public int FieldType { get; set; }
    public bool IsRequired { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public int CreatedByUserID { get; set; }
    public Nullable<System.DateTime> UpdatedDT { get; set; }
    public Nullable<int> UpdatedByUserID { get; set; }
    public bool IsDeleted { get; set; }
    public string Choices { get; set; }
    public int QuoteTypeID { get; set; }
    public bool ShowCustomer { get; set; }
    public bool ShowVendors { get; set; }
}

public partial class FinalRates
{
    public int RFQID { get; set; }
    public int ComponentID { get; set; }
    public decimal AcceptedCost { get; set; }
    public decimal ActualCost { get; set; }
    public bool IsDeleted { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public int CreatedByUserID { get; set; }
    public string Rates { get; set; }
}

public partial class Quotations
{
    public int QuoteID { get; set; }
    public int RequestForQuoteID { get; set; }
    public int TransporterID { get; set; }
    public int AcceptID { get; set; }
    public bool IsAcceptedByExeOrCust { get; set; }
    public decimal Charges { get; set; }
    public string PaymentTerms { get; set; }
    public string Status { get; set; }
    public System.DateTime AcceptanceStatusOn { get; set; }
    public Nullable<System.DateTime> ExtendDeliveryDT { get; set; }
    public string Notes { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public System.DateTime UpdatedDT { get; set; }
    public bool IsDeleted { get; set; }
    public string Components { get; set; }
    public decimal ExchangeRate { get; set; }
    public string AcceptNote { get; set; }
    public int RoundNumber { get; set; }
    public string NegotiationComments { get; set; }
    public bool IsNegotiated { get; set; }
}

public partial class QuoteType
{
    public int QuoteTypeID { get; set; }
    public string QuoteTypeName { get; set; }
    public string PaidBy { get; set; }
    public string Type { get; set; }
    public bool IsDeleted { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public int CreatedByUserID { get; set; }
    public Nullable<System.DateTime> LastUpdatedDT { get; set; }
    public Nullable<int> LastUpdatedByUserID { get; set; }
    public bool IsAllowNegotiation { get; set; }
    public int ServiceTypeID { get; set; }
    public string CoreField { get; set; }
}

public partial class QuoteTypeComponent
{
    public int ComponentID { get; set; }
    public string ComponentName { get; set; }
    public string Type { get; set; }
    public string PaidBy { get; set; }
    public string Currency { get; set; }
    public int QuoteTypeID { get; set; }
    public bool IsDeleted { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public int CreatedByUserID { get; set; }
    public Nullable<System.DateTime> LastUpdatedDT { get; set; }
    public Nullable<int> LastUpdatedByUserID { get; set; }
}

public partial class Rating
{
    public int RFQID { get; set; }
    public int Stars { get; set; }
    public string Reason { get; set; }
    public string RatingData { get; set; }
}

public partial class RFQ
{
    public int RequestForQuoteID { get; set; }
    public int CustomerID { get; set; }
    public int SourceID { get; set; }
    public int ExecutiveID { get; set; }
    public string Destination { get; set; }
    public string Source { get; set; }
    public string Product { get; set; }
    public System.DateTime PickUp { get; set; }
    public System.DateTime DeliveryBy { get; set; }
    public bool AllowLaterDelivery { get; set; }
    public System.DateTime QuoteBy { get; set; }
    public string Details { get; set; }
    public string Status { get; set; }
    public string Transporters { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public System.DateTime UpdatedDT { get; set; }
    public bool IsDeleted { get; set; }
    public bool CloseEarly { get; set; }
    public string OrderNo { get; set; }
    public string FileName { get; set; }
    public int RouteID { get; set; }
    public string Route { get; set; }
    public int DispatchedByUserID { get; set; }
    public Nullable<System.DateTime> DispatchedDT { get; set; }
    public int ZoneID { get; set; }
    public int ForwardedByUserId { get; set; }
    public Nullable<System.DateTime> ClearenceDT { get; set; }
    public int ClearedByUserID { get; set; }
    public Nullable<System.DateTime> TimeSlotFromDT { get; set; }
    public Nullable<System.DateTime> TimeSlotToDT { get; set; }
    public Nullable<System.DateTime> VehicleReadyDT { get; set; }
    public string VehicleNumber { get; set; }
    public int VehReadyByUserID { get; set; }
    public Nullable<System.DateTime> VehicleEntryDT { get; set; }
    public int LoadingByUserID { get; set; }
    public int ReadyByTransporterUserID { get; set; }
    public int QuoteTypeID { get; set; }
    public int PaymentTerm { get; set; }
    public string FixedTerm { get; set; }
    public Nullable<System.DateTime> ReminderSentDT { get; set; }
    public decimal Budget { get; set; }
    public int ShipmentID { get; set; }
    public Nullable<System.DateTime> StartWorkDT { get; set; }
    public int StartedByUserID { get; set; }
    public Nullable<System.DateTime> CompletionDT { get; set; }
    public int CompletionByUserID { get; set; }
}

public partial class RFQFieldValue
{
    public int RFQFieldID { get; set; }
    public int RFQID { get; set; }
    public int FieldID { get; set; }
    public string FieldValue { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public int CreatedUserID { get; set; }
    public Nullable<System.DateTime> UpdatedDT { get; set; }
    public Nullable<int> UpdatedUserID { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class Route
{
    public int RouteID { get; set; }
    public string RouteCode { get; set; }
    public string RouteDetail { get; set; }
    public bool IsDeleted { get; set; }
    public System.DateTime CreatedDT { get; set; }
}

public partial class ServiceType
{
    public int ServiceTypeID { get; set; }
    public string ServiceName { get; set; }
    public bool IsDeleted { get; set; }
    public string CompletionDateText { get; set; }
    public string PickupDateText { get; set; }
}

public partial class ShipField
{
    public int ShipFieldID { get; set; }
    public int QuoteTypeID { get; set; }
    public string PickupDTName { get; set; }
    public string ProductName { get; set; }
    public string SourceLocationName { get; set; }
    public string SourceAddressName { get; set; }
    public string DestinationName { get; set; }
    public string ContainerName { get; set; }
    public string PortofLoadingName { get; set; }
    public string PortofDischargeName { get; set; }
    public string EmtcontainPickupName { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class Shipment
{
    public int ShipmentID { get; set; }
    public int QuoteID { get; set; }
    public int RFQID { get; set; }
    public int TransporterID { get; set; }
    public int QuoteTypeID { get; set; }
    public Nullable<System.DateTime> PickupDT { get; set; }
    public string Product { get; set; }
    public string SourceLocation { get; set; }
    public string SourceAddress { get; set; }
    public string DestinationAddress { get; set; }
    public int Containers { get; set; }
    public string PortofLoading { get; set; }
    public string PortofDischarge { get; set; }
    public string EmptyContainer { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public int CreatedByUserID { get; set; }
    public bool IsDeleted { get; set; }
    public string ServiceIDs { get; set; }
    public System.DateTime DeliveryDT { get; set; }
    public int CustomerID { get; set; }
    public string ShipmentRFQIDs { get; set; }
    public string FileName { get; set; }
    public string Status { get; set; }
    public int UpdatedByUserID { get; set; }
    public Nullable<System.DateTime> UpdatedDT { get; set; }
}

public partial class Slot
{
    public int SlotID { get; set; }
    public System.TimeSpan SlotFrom { get; set; }
    public System.TimeSpan SlotTo { get; set; }
    public int Capacity { get; set; }
    public int ServiceTypeID { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public int CreatedByUserID { get; set; }
    public Nullable<System.DateTime> UpdatedDT { get; set; }
    public int UpdatedByUserID { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class Source
{
    public int SourceID { get; set; }
    public string Location { get; set; }
    public string Type { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Notes { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public System.DateTime UpdatedDT { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class Transporter
{
    public int TransporterID { get; set; }
    public string CompanyName { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Mobile { get; set; }
    public string AlternateMobile { get; set; }
    public string Password { get; set; }
    public string Notes { get; set; }
    public System.DateTime CreatedDT { get; set; }
    public System.DateTime UpdatedDT { get; set; }
    public bool IsDeleted { get; set; }
    public bool IsDomestic { get; set; }
    public bool IsExport { get; set; }
    public string ServiceTypeID { get; set; }
}

public partial class Zone
{
    public int ZoneID { get; set; }
    public string ZoneName { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class getTransporterQuoteDetail_Result
{
    public int reqForQuoteID { get; set; }
    public Nullable<int> customerID { get; set; }
    public string customerName { get; set; }
    public System.DateTime quoteByDT { get; set; }
    public string details { get; set; }
    public string status { get; set; }
    public bool isCloseEarly { get; set; }
    public string orderNo { get; set; }
    public string fileName { get; set; }
    public int paymentTerm { get; set; }
    public string fixedTerm { get; set; }
    public Nullable<System.DateTime> reminderSentDate { get; set; }
    public System.DateTime pickupDT { get; set; }
    public string fields { get; set; }
    public string components { get; set; }
    public System.DateTime deliveryDT { get; set; }
}

public partial class sp_getAllocatedSlotDetail_Result
{
    public int containerID { get; set; }
    public int shipmentID { get; set; }
    public Nullable<System.TimeSpan> scheduleTime { get; set; }
    public string transporterName { get; set; }
    public string customerName { get; set; }
}

public partial class sp_getCountRFQ_Result
{
    public int Status { get; set; }
    public Nullable<int> RFQcount { get; set; }
}

public partial class sp_getDispatchPlanList_Result
{
    public int shipmentID { get; set; }
    public Nullable<System.DateTime> pickup { get; set; }
    public string source { get; set; }
    public int container { get; set; }
    public string fileName { get; set; }
    public int customerID { get; set; }
    public string companyName { get; set; }
    public string serviceName { get; set; }
    public int serviceTypeID { get; set; }
    public System.DateTime delivery { get; set; }
    public string serviceIDs { get; set; }
    public string product { get; set; }
    public string sourceAddress { get; set; }
    public string destination { get; set; }
    public string portofLoading { get; set; }
    public string portofDischarge { get; set; }
    public string emptyContainer { get; set; }
}

public partial class sp_getRequest_Result
{
    public int RequestForQuoteID { get; set; }
    public string Source { get; set; }
    public string Location { get; set; }
    public string SourceAddress1 { get; set; }
    public string SourceAddress2 { get; set; }
    public string Destination { get; set; }
    public string Product { get; set; }
    public bool AllowLaterDelivery { get; set; }
    public int CustomerID { get; set; }
    public bool CloseEarly { get; set; }
    public string CompanyName { get; set; }
    public string DestinationAddress1 { get; set; }
    public string DestinationAddress2 { get; set; }
    public string CustomerCity { get; set; }
    public string CustomerState { get; set; }
    public string SourceCity { get; set; }
    public string SourceState { get; set; }
    public System.DateTime PickUp { get; set; }
    public System.DateTime DeliveryBy { get; set; }
    public System.DateTime QuoteBy { get; set; }
    public string Details { get; set; }
    public string Status { get; set; }
    public decimal Charges { get; set; }
    public string PaymentTerms { get; set; }
    public string Notes { get; set; }
    public System.DateTime ExtendDeliveryDT { get; set; }
    public string QuoteStatus { get; set; }
    public string OrderNo { get; set; }
    public string FileName { get; set; }
    public string RouteName { get; set; }
}

public partial class sp_getRFQList_Result
{
    public int reqForQuoteID { get; set; }
    public Nullable<int> customerID { get; set; }
    public string customerName { get; set; }
    public System.DateTime quoteByDT { get; set; }
    public string details { get; set; }
    public string status { get; set; }
    public string transporterIDs { get; set; }
    public bool isCloseEarly { get; set; }
    public string orderNo { get; set; }
    public string fileName { get; set; }
    public Nullable<System.DateTime> timeSlotFromDT { get; set; }
    public Nullable<System.DateTime> timeSlotToDT { get; set; }
    public int vehReadyByUserID { get; set; }
    public Nullable<System.DateTime> vehicleEntryDT { get; set; }
    public Nullable<System.DateTime> clearanceDT { get; set; }
    public string vehicleNumber { get; set; }
    public int paymentTerm { get; set; }
    public string fixedTerm { get; set; }
    public Nullable<System.DateTime> reminderSentDate { get; set; }
    public string fields { get; set; }
    public string transporterDetail { get; set; }
    public string response { get; set; }
    public string createdBy { get; set; }
    public string dispatchedBy { get; set; }
    public string destinationAddress { get; set; }
    public System.DateTime deliveryDT { get; set; }
    public Nullable<System.DateTime> dispatchDT { get; set; }
    public System.DateTime pickUpDT { get; set; }
    public decimal budget { get; set; }
    public string serviceName { get; set; }
    public Nullable<System.DateTime> startWorkDT { get; set; }
}

public partial class sp_getScheduleList_Result
{
    public string CompanyName { get; set; }
    public Nullable<System.DateTime> TimeSlotFromDT { get; set; }
    public Nullable<System.DateTime> TimeSlotToDT { get; set; }
}

public partial class sp_getTransportRFQ_Result
{
    public int shipmentID { get; set; }
    public int rfqID { get; set; }
    public int quoteID { get; set; }
    public System.DateTime pickupDate { get; set; }
    public string product { get; set; }
    public string sourceAddress { get; set; }
    public string sourceLocation { get; set; }
    public string destinationAddress { get; set; }
    public string emptyContainer { get; set; }
    public int containers { get; set; }
    public string portofDischarge { get; set; }
    public string portodLoading { get; set; }
    public System.DateTime deliveryDate { get; set; }
    public string detail { get; set; }
    public int executiveID { get; set; }
    public string fixedTerm { get; set; }
    public string fileName { get; set; }
    public int customerID { get; set; }
    public string orderNo { get; set; }
    public string status { get; set; }
    public string transportCompany { get; set; }
    public string customerCompany { get; set; }
    public string components { get; set; }
    public string paymentTerms { get; set; }
    public System.DateTime quoteBy { get; set; }
    public int loadingbyUserID { get; set; }
    public int clearedByUserID { get; set; }
    public Nullable<System.DateTime> clearenceDT { get; set; }
    public Nullable<System.DateTime> timeFromDT { get; set; }
    public Nullable<System.DateTime> timeToDT { get; set; }
    public int vehReadyByUserID { get; set; }
    public Nullable<System.DateTime> vehicleEntryDT { get; set; }
    public string vehicleNumber { get; set; }
    public Nullable<System.DateTime> vehicleReadyDT { get; set; }
    public Nullable<System.DateTime> dispatchedDT { get; set; }
    public int dispatchedByUserID { get; set; }
    public string transporterDetail { get; set; }
    public string response { get; set; }
    public string createdBy { get; set; }
    public string vendorName { get; set; }
    public decimal exchangeRate { get; set; }
}

public partial class sp_MapShipFields_Result
{
    public int ShimpmentID { get; set; }
    public string Msg { get; set; }
}
